version: '3.8'

# DockerCompose pour la création et la configuration du Media Serveur
# Liste des services :
# PLEX
# Radarr
# Sonarr
# Lidarr
# Bazarr
# Prowlarr
# Qbitorrent


services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/plex/library:/config     
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    entrypoint: /entrypoint.sh    # Script d'entrée pour monter le partage
    restart: unless-stopped

# chmod +x entrypoint.sh

#======= ENTRY POINT =========================================================================================================
#!/bin/bash

## Monter le partage réseau
#mkdir -p /media/data
#mount -t cifs -o "username=user,password=pass,iocharset=utf8" //10.0.50.40/data /media/data

## Démarrer Plex
#exec /init
#=============================================================================================================================